### ISSUE TITLE
Error when minify solid js

### ISSUE THREAD

**Issue by sirenkovladd** [putoutjs/minify#17]
- **Version** (`npm -v`): 10.5.2
- **Node Version** `node -v`: v20.13.1
- **OS** (`uname -a` on Linux): Darwin arm64

Small reproduce
```js
import { minify } from "@putout/minify";

const source = `export function mergeProps() {
  let n = a();
  if (n) {
    n()
  }
  if (true) {
    const n = b();
    if (n) n();
  }
}`;
const result = minify(source);

```

```sh
TypeError: Cannot read properties of undefined (reading 'buildError')
    at e.value (~/node_modules/@putout/minify/bundle/minify.min.js:1:886385)
    at e.value (~/node_modules/@putout/minify/bundle/minify.min.js:1:890422)
    at e.value (~/node_modules/@putout/minify/bundle/minify.min.js:1:888346)
    at Object.Declaration (~/node_modules/@putout/minify/bundle/minify.min.js:1:881622)
    at e._call (~/node_modules/@putout/minify/bundle/minify.min.js:1:946995)
    at e.call (~/node_modules/@putout/minify/bundle/minify.min.js:1:946754)
    at e.visit2 [as visit] (~/node_modules/@putout/minify/bundle/minify.min.js:1:947999)
    at e.value (~/node_modules/@putout/minify/bundle/minify.min.js:1:978435)
    at e.value (~/node_modules/@putout/minify/bundle/minify.min.js:1:978023)
    at e.value (~/node_modules/@putout/minify/bundle/minify.min.js:1:978713) {
  loc: { line: 7, column: 4 },
  rule: 'minify/convert-const-to-var'
}
```

**Comment by coderaiser** [comment]
Just fixed in `@putout/minify` [v3.15.0](https://github.com/putoutjs/minify/releases/tag/v3.14.0) 🎉.

Is it works for you?

**Comment by sirenkovladd** [comment]
Now it's broken

```js
import { minify } from "@putout/minify";

const source = `function on(e) {
  const r = Array.isArray(e);
  return r;
}
const DEV = void 0;
console.log({DEV,on});
`;

eval(source);
console.log('---');
const result = minify(source);
console.log(result);
eval(result);
```

here's the library I'm trying to minify
https://cdn.jsdelivr.net/npm/solid-js@1.8.17/dist/solid.min.js

**Comment by coderaiser** [comment]
Please provide code examples of what you receive and what you expect

**Comment by coderaiser** [comment]
anded in [v3.19.2](https://github.com/putoutjs/minify/releases/tag/v3.19.2) 🎉. Is it works for you?

**Comment by sirenkovladd** [comment]
Nice, thank you
