### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by alexhochreiter** [putoutjs/minify#29]
- **Version** (`npm -v`): 4.8.3
- **Node Version** `node -v`: 20.18.1
- **OS** (`uname -a` on Linux): Linux youwish 6.11.5-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Oct 22 19:13:11 UTC 2024 x86_64 GNU/Linux

I am having trouble minifying a .mjs file.
```
import { minify } from '@putout/minify';        
const minifedContent = minify(fs.readFileSync('...../file.mjs', { encoding: 'utf8' }))
console.log('--------------------------------------------------')
console.log(minifedContent)
process.exit(0)
```

There is an error thrown at `minify`:
```
ReferenceError: require is not defined
    at file:///mypro/node_modules/@putout/minify/bundle/minify.min.js:13:736
    at t (file:///mypro/node_modules/@putout/minify/bundle/minify.min.js:10:4262)
    at H2 (file:///mypro/node_modules/@putout/minify/bundle/minify.min.js:13:826)
    at file:///mypro/node_modules/@putout/minify/bundle/minify.min.js:13:311
    at file:///mypro/node_modules/@putout/minify/bundle/minify.min.js:13:395
    at file:///mypro/node_modules/@putout/minify/bundle/minify.min.js:13:9173
    at HK.loadPlugins (file:///mypro/node_modules/@putout/minify/bundle/minify.min.js:13:9379)
    at er5.transform (file:///mypro/node_modules/@putout/minify/bundle/minify.min.js:14:16581)
    at evn (file:///mypro/node_modules/@putout/minify/bundle/minify.min.js:52:5843)
    at scanDir (file:///mypro/build-scripts/myscript.mjs:63:38)
```

is this library able to be used from an `ESM` enviroment?

When using a dedicated reproduceable file like this:
```
import { minify } from '@putout/minify'
const data = minify('export default function abbbbb() { return 3333;}')
console.log(data)
```

I am receiving the following error:
```
ReferenceError: require is not defined in ES module scope, you can use import instead
```

**Comment by coderaiser** [comment]
Just fixed with [9321477](https://github.com/putoutjs/minify/commit/93214773574da9676064b753d0c1f1305626d8e7), Landed in [v4.8.4](https://github.com/putoutjs/minify/releases/tag/v4.8.4) 🎉 . Is it works for you?

**Comment by alexhochreiter** [comment]
yes! it is now working as intented. 
thank you very much for your fast response!

**Comment by alexhochreiter** [comment]
yes! it is now working as intented.
thank you very much for your fast response!
